#ifndef RESOLUTION_HPP
#define RESOLUTION_HPP


#if (RESOLUTION_QUALITY == 1440)
	#define DEFAULT_SCREEN_WIDTH 2560
	#define DEFAULT_SCREEN_HEIGHT 1440

#elif (RESOLUTION_QUALITY == 1296)
	#define DEFAULT_SCREEN_WIDTH 2304	
	#define DEFAULT_SCREEN_HEIGHT 1296

#elif (RESOLUTION_QUALITY == 1152)
	#define DEFAULT_SCREEN_WIDTH 2048	
	#define DEFAULT_SCREEN_HEIGHT 1152

#elif (RESOLUTION_QUALITY == 1080)
	#define DEFAULT_SCREEN_WIDTH 1920
	#define DEFAULT_SCREEN_HEIGHT 1080

#elif (RESOLUTION_QUALITY == 900)
	#define DEFAULT_SCREEN_WIDTH 1600
	#define DEFAULT_SCREEN_HEIGHT 900

#elif (RESOLUTION_QUALITY == 768)
	#define DEFAULT_SCREEN_WIDTH 1366
	#define DEFAULT_SCREEN_HEIGHT 768

#elif (RESOLUTION_QUALITY == 720)
	#define DEFAULT_SCREEN_WIDTH 1280
	#define DEFAULT_SCREEN_HEIGHT 720

#else //DEFAULT
	#define DEFAULT_SCREEN_WIDTH 1920
	#define DEFAULT_SCREEN_HEIGHT 1080

#endif //RESOLUTION_QUALITY


#endif //RESOLUTION_HPP