#ifndef TEXTURE_TYPES_HPP
#define TEXTURE_TYPES_HPP


namespace Engine{
	namespace Textures{

		enum TextureType{
			TEXTURE_UNKNOWN = 0,
			TEXTURE_DIFFUSE,
			TEXTURE_ALBEDO,
			TEXTURE_SPECULAR,
			TEXTURE_NORMAL,
			TEXTURE_METALLIC,
			TEXTURE_ROUGHNESS,
			TEXTURE_OCCLUSION,
			TEXTURE_HEIGHT,
			TEXTURE_DEPTH,
			TEXTURE_OPACITY,
			TEXTURE_FRAMEBUFFER,
			TEXTURE_TEXT,
			TEXTURE_LOCATION
		};

	}
}

#endif //TEXTURE_TYPES_HPP